name: Eval /ask endpoint

on:
  pull_request:
    branches: [ main ]

jobs:
  eval-ask:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests
      - name: Import app smoke
        run: python -c "import app; print('app import OK')"
      - name: Run eval-ask
        run: make eval-ask
      - name: Upload eval results
        uses: actions/upload-artifact@v4
        with:
          name: eval_ask.json
          path: out/eval_ask.json
