name: Evaluation Gate

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Smoke import
        run: python -c "import app; print('app import OK')"

      - name: Run evaluation gate (continue on error to upload artifacts)
        id: eval
        continue-on-error: true
        run: |
          make eval-gate

      - name: Upload eval artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eval-artifacts
          path: |
            data/eval/latest_metrics.json
            data/eval/latest_metrics.md
          if-no-files-found: warn

      - name: Fail if gate failed
        if: steps.eval.outcome == 'failure'
        run: |
          echo "Evaluation gate failed. See artifacts." >&2
          exit 2
